movietag/movie/urls.py
#-*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

from . import views

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'movietag.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', views.movie_list, name='movie_list'),
    url(r'^search/$', views.movie_search_default, name='movie_search_default'),
    url(r'^search/(?P<text>[\w]+)/$', views.movie_search, name='movie_search'),
)

movietag/movietag/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

from movie import views as m_views

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'movietag.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    #url(r'^$', 'movie.views.index', name='index'),
    url(r'^$', 'movie.views.movie_search_default', name='index'),

    url(r'^m/', include('movie.urls', namespace='movie')),

    url(r'^admin/', include(admin.site.urls)),
)

movietag/movie/models.py
#-*- coding: utf-8 -*-
import uuid
import base64

from django.db import models
from djangotoolbox.fields import ListField

from account.models import Account

# Create your models here.
class Movie(models.Model):
    title = models.CharField(max_length=100)
    title_aka = models.CharField(max_length=100, null=True, blank=True)
    title_eng = models.CharField(max_length=100, null=True, blank=True)
    title_url = models.SlugField(max_length=50)

    year = models.IntegerField(default=-1, null=True)
    running_time = models.IntegerField(default=-1, null=True)
    released_at = models.DateField(null=True)
    re_released_at = models.DateField(null=True)

    rating = models.FloatField(default=0)
    other_rating = models.FloatField(default=0)

    poster_big = models.URLField(null=True, blank=True)
    stillcut_big = models.URLField(null=True, blank=True)

    youtube_id = models.CharField(max_length=30, null=True, blank=True)

    unique_id = models.CharField(max_length=10)

    main_genre = models.ForeignKey('Genre', null=True)
    sub_genre_set = models.ManyToManyField('Genre', related_name='sub_genre')
    
    def save(self, *args, **kwargs):
        if not self.unique_id:
            while True:
                unique_id = base64.b64encode(str(uuid.uuid4()))[:10]
                m = Movie.objects.filter(unique_id=unique_id)

                if len(m) is 0:
                    self.unique_id = unique_id
                    break

        super(Movie, self).save(*args, **kwargs)

    def __unicode__(self):
        return "%s (%s)" % (self.title, self.title_eng)

class Genre(models.Model):
    text = models.CharField(max_length=30)

    def __unicode__(self):
        return "%s" % (self.text)

class Tag(models.Model):
    text = models.CharField(max_length=30)

    movie_set = models.ManyToManyField(Movie)

    def __unicode__(self):
        return "%s" % (self.text)

class Frequency(models.Model):
    tag = models.ForeignKey(Tag)
    movie = models.ForeignKey(Movie, null=True)

    freq = models.IntegerField(default=0)
    like_user = models.ManyToManyField(Account)

    def __unicode__(self):
        return "%s - %s" % (self.tag.text, self.freq)

movietag/movie/views.py
#-*- coding: utf-8 -*-
from django.shortcuts import render, redirect, render_to_response, RequestContext, HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse

from .models import Movie, Genre, Tag, Frequency

from utils.func import *

#######################
# mongo-engine
#######################

from mongoengine import connect, Document, DictField, ListField

connect('carpedm20')

class Movie(Document):
    info = DictField()
    tags = ListField(DictField())

# Django version
def add_freq_to_movie_list(movie_list):
    for movie in movie_list:
        movie.top_freqs = []

        tag_set = movie.tag_set.all()

        try:
            for tag in tag_set[len(tag_set)-9:len(tag_set)]:
                if tag.text == u'영화':
                    continue

                freqs = Frequency.objects.filter(movie=movie, tag=tag)

                for f in freqs:
                    movie.top_freqs.append(f)
        except:
            pass

        if 'default' in movie.poster_big:
            pass
            #movie.poster_big = "http://www.seenth.at/img/st_default_poster_chatter.png"
    return movie_list

def index(request):
    template = 'index.html'

    return render(request, template)

def movie_search_default(request):
    return movie_search(request, u"첫사랑")

def movie_search(request, text):
    """
    Version 3 (MongoDB)
    """
    template = 'movie/movie_list_mongo.html'
    page_template = 'movie/movie_item_mongo.html'

    movie_list = Movie.objects(__raw__={"tags.%s" %text:{"$gt":0}})

    movie_list = movie_list[:40]

    new_movie_list = []

    for movie in movie_list:
        m = {}
        m['title'] = movie.info['title']
        m['other_rating'] = movie.info['watcha_rating']
        m['poster'] = movie.info['poster']['big']

        m['tags'] = []

        count = 0
        MAX_COUNT = 9
        main_tag_find = False

        l = movie.tags

        for tag in l[::-1]:
            if count > MAX_COUNT and main_tag_find:
                break

            key = tag.keys()[0]
            value = tag.values()[0]

            if key == u'영화':
                continue

            if key == text:
                m['main_key'] = key
                m['main_value'] = value

                main_tag_find = True
                continue

            if count > MAX_COUNT:
                continue

            t = {'key':key, 'value':value}
            m['tags'].append(t)
            count += 1

        new_movie_list.append(m)

    try:
        new_movie_list = sorted(new_movie_list, key=lambda k: k['main_value'])
    except:
        pass

    """
    Version 2

    template = 'movie/movie_list.html'
    page_template = 'movie/movie_item.html'

    #tag = Tag.objects.get(text=text)
    freqs = Frequency.objects.filter(tag__text=text)

    movie_list = []

    for freq in freqs:
        if freq.freq == 1:
           continue

        movie_list.append(freq.movie)

    movie_list = add_freq_to_movie_list(movie_list[:20])

    """

    """
    Version 1

    for movie in tag.movie_set.all():
        try:
            freq = Frequency.objects.get(movie=movie, tag=tag)
        except:
            freq = Frequency.objects.filter(movie=movie, tag=tag)[0]

        if freq.freq == 1:
            continue

        movie_list.append(movie)

    #movie_list = movie_list[:100]
    """

    current_account = get_account_from_user(request.user)

    data = {'movie_list': new_movie_list, }

    return render(request, template, data)

def movie_list(request):
    context = RequestContext(request)
    template = 'movie/movie_list.html'

    movie_list = Movie.objects.all()[30000:30090]

    movie_list = add_freq_to_movie_list(movie_list)

    current_account = get_account_from_user(request.user)

    data = {'movie_list' : movie_list, }

    return render(request, template, data)

movietag/templates/movie/movie_item.html
{% block movie_li %}

{% for movie in movie_list reversed %}
  <!--<div class="poster col-md-3 col-sm-4 col-xs-6">-->
  <div class="poster col-md-3 col-sm-4 col-xs-12">
    <img class="img-poster" src="{{ movie.poster_big }}" alt="{{ movie.title }}">
    <a class="frame" href="#" title="{{ movie.title }}">
      <span class="frame-title">{{ movie.title }}</span>
      <span class="overlay"></span>
    </a>
    <div class="raty text-center" data-score="{{ movie.other_rating }}"></div>
    <div class="film-stats">
      <ul class="list-group">
        {% for freq in movie.top_freqs reversed %}
          <li class="list-group-item">
            <span class="badge">{{ freq.freq }}</span>
            <a href="{% url 'movie:movie_search' freq.tag.text %}">
              {{ freq.tag }}
            </a>
          </li>
        {% endfor %}
      </ul>
    </div>
  </div>
{% endfor %}

{% endblock %}

movietag/templates/movie/movie_item_mongo.html
{% block movie_li %}

{% for movie in movie_list reversed %}
  <!--<div class="poster col-md-3 col-sm-4 col-xs-6">-->
  <div class="poster col-md-3 col-sm-4 col-xs-12">
    <img class="img-poster" src="{{ movie.poster }}" alt="{{ movie.title }}">
    <a class="frame" href="#" title="{{ movie.title }}">
      <span class="frame-title">{{ movie.title }}</span>
      <span class="overlay"></span>
    </a>
    <div class="raty text-center" data-score="{{ movie.other_rating }}"></div>
    <div class="film-stats">
      <ul class="list-group">
        <li class="list-group-item list-group-item-success">
          <span class="badge">{{ movie.main_value }}</span>
          <a href="{% url 'movie:movie_search' movie.main_key %}">
            {{ movie.main_key }}
          </a>
        </li>
        {% for freq in movie.tags %}
          <li class="list-group-item">
            <span class="badge">{{ freq.value }}</span>
            <a href="{% url 'movie:movie_search' freq.key %}">
              {{ freq.key }}
            </a>
          </li>
        {% endfor %}
      </ul>
    </div>
  </div>
{% endfor %}

{% endblock %}

movietag/templates/movie/movie_list.html
{% extends 'base.html' %}

{% block content %}

{% include 'navbar.html' %}

<div class="container">
  <div class="content">
    {% include 'movie/movie_item.html' with movie_list=movie_list %}
  </div>
</div>

{% endblock %}

movietag/templates/movie/movie_list_mongo.html
{% extends 'base.html' %}

{% block content %}

{% include 'navbar.html' %}

<div class="container">
  <div class="content">
    {% include 'movie/movie_item_mongo.html' with movie_list=movie_list %}
  </div>
</div>

{% endblock %}